# Generated by Django 5.2.14 on 2026-08-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_widen_workflow_integer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name='department',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='service_provider',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name='name of service provider',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='service_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('marketing', 'Marketing'),
                    ('loan', 'Loan'),
                    ('guarantee', 'Guarantee'),
                ],
                db_index=True,
                max_length=50,
                null=True,
                verbose_name='type of service',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='start_date',
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='start date',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='tenure',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='tenure',
            ),
        ),
    ]